Feature/derp 238 iframe component
GreaterLondonAuthority/accelerator-core-alpha pull request #48
Opened 2021-08-04 22:01 UTC by lukewhitmore

Issue [here](https://london.atlassian.net/browse/DERP-238)

2021-08-09 16:27 UTC, philwolstenholme requested changes
Some UUIDs have snuck into the config @lukewhitmore 

We'll need to sort out permissions at some point but I see there's https://london.atlassian.net/browse/DERP-615 for that

2021-08-10 14:24 UTC, philwolstenholme commented
@lukewhitmore I think we'll also need a way to add this compone to a page so it can be tested.

Eventually it'll be added to the components field on the Page section paragraph, but for now you could add it to the Paragraphs field on the Generic content node bundle.

2021-08-10 14:45 UTC, joz-cti requested changes

2021-08-10 14:45 UTC, joz-cti commented on config/install/core.entity_form_display.paragraph.iframe.default.yml
> +uuid: 64576820-d1d8-4f25-95ec-5c262170ab44
This needs to be removed from Core?

2021-08-10 14:45 UTC, joz-cti commented on config/install/core.entity_form_display.paragraph.iframe.default.yml
> +_core:
This needs to be removed from Core?

2021-08-12 15:31 UTC, lukewhitmore commented on config/install/core.entity_form_display.paragraph.iframe.default.yml
> +uuid: 64576820-d1d8-4f25-95ec-5c262170ab44
Thanks .. now removing these using sed.

2021-08-12 16:34 UTC, joz-cti approved these changes

2021-08-12 16:54 UTC, philwolstenholme approved these changes

2021-08-12 16:55 UTC, merged